const FETCH_AUTHOR_REQUEST = 'FETCH_AUTHOR_REQUEST';
const FETCH_AUTHOR_SUCCESS = 'FETCH_AUTHOR_SUCCESS';
const SELECT_ITEM = 'SELECT_ITEM';
const CHANGE_ITEM = 'CHANGE_ITEM';
const DELETE_ITEM = 'DELETE_ITEM';
const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
const CLEAR_SELECTION = 'CLEAR_SELECTION';
const MOVE_SELECTION_UP = 'MOVE_SELECTION_UP';
const MOVE_SELECTION_DOWN = 'MOVE_SELECTION_DOWN';

export {
  FETCH_AUTHOR_REQUEST,
  FETCH_AUTHOR_SUCCESS,
  SELECT_ITEM,
  CLEAR_SELECTION,
  CHANGE_ITEM,
  DELETE_ITEM,
  CHANGE_INPUT_VALUE,
  MOVE_SELECTION_UP,
  MOVE_SELECTION_DOWN
};
